spring.application.name=trading-platform
server.port=5454

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/crypto_trading_platform?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=your_database_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@gmail.com
spring.mail.password=your_gmail_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Stripe
stripe.api.key=your_stripe_api_key

# Razorpay
razorpay.api.key=your_razorpay_key
razorpay.api.secret=your_razorpay_secret

# CoinGecko
coingecko.api.key=your_coingecko_api_key

# Gemini
gemini.api.key=your_gemini_api_key

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=your_google_client_id
spring.security.oauth2.client.registration.google.client-secret=your_google_client_secret

# Frontend
app.frontend.url=http://localhost:5173